[project]
authors = [{name = "sagitta42", email = "mariia.redchuk@gmail.com"}]
dependencies = [
  "poetry (>=2.3.4,<3.0.0)",
  "dotenv (>=0.9.9,<0.10.0)",
  "pyyaml (>=6.0.3,<7.0.0)",
  "pydantic (>=2.13.4,<3.0.0)",
  "send2trash (>=2.1.0,<3.0.0)",
  "pydantic-parse (==0.1.2)",
]
description = "Higher level wrapper for poetry for smart install operations and advanced package template creation"
name = "poetiq"
readme = "README.md"
requires-python = ">=3.12,<4.0"
version = "0.1.3"

[tool.poetry]
include = [
  {path = "src/poetiq/_build_assets/**/*", format = [
    "sdist",
    "wheel",
  ]},
]
packages = [{include = "poetiq", from = "src"}]

[tool.poetry.build]
generate-setup-file = false
script = "build.py"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=2.0.0,<3.0.0"]

[dependency-groups]
dev = ["pytest (>=9.1.1,<10.0.0)"]

[project.scripts]
poetiq = "poetiq.__main__:main"
